version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - godot
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should have a package comment
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
