// Code generated by gen-api-client. DO NOT EDIT.
package com.caic.sdk

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

typealias Harness = String

object Harnesses {
    const val Claude: Harness = "claude"
    const val Gemini: Harness = "gemini"
}

typealias EventKind = String

object EventKinds {
    const val Init: EventKind = "init"
    const val Text: EventKind = "text"
    const val TextDelta: EventKind = "textDelta"
    const val ToolUse: EventKind = "toolUse"
    const val ToolResult: EventKind = "toolResult"
    const val Ask: EventKind = "ask"
    const val Usage: EventKind = "usage"
    const val Result: EventKind = "result"
    const val System: EventKind = "system"
    const val UserInput: EventKind = "userInput"
    const val Todo: EventKind = "todo"
}

typealias ClaudeEventKind = EventKind

object ErrorCodes {
    const val BadRequest = "BAD_REQUEST"
    const val NotFound = "NOT_FOUND"
    const val Conflict = "CONFLICT"
    const val InternalError = "INTERNAL_ERROR"
}

@Serializable
data class HarnessJSON(
    val name: String,
    val models: List<String>,
)

@Serializable
data class RepoJSON(
    val path: String,
    val baseBranch: String,
    @SerialName("repoURL") val repoURL: String? = null,
)

@Serializable
data class TaskJSON(
    val id: String,
    val task: String,
    val repo: String,
    @SerialName("repoURL") val repoURL: String? = null,
    val branch: String,
    val container: String,
    val state: String,
    val stateUpdatedAt: Double,
    val diffStat: List<DiffFileStat>? = null,
    @SerialName("costUSD") val costUSD: Double,
    val durationMs: Long,
    val numTurns: Int,
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheCreationInputTokens: Int,
    val cacheReadInputTokens: Int,
    val error: String? = null,
    val result: String? = null,
    val harness: Harness,
    val model: String? = null,
    val agentVersion: String? = null,
    @SerialName("sessionID") val sessionID: String? = null,
    val containerUptimeMs: Long? = null,
    val inPlanMode: Boolean? = null,
)

@Serializable
data class StatusResp(val status: String)

@Serializable
data class CreateTaskResp(val status: String, val id: String)

@Serializable
data class CreateTaskReq(
    val prompt: String,
    val repo: String,
    val model: String? = null,
    val harness: Harness,
    val image: String? = null,
)

@Serializable
data class InputReq(val prompt: String)

@Serializable
data class RestartReq(val prompt: String)

@Serializable
data class DiffFileStat(
    val path: String,
    val added: Int,
    val deleted: Int,
    val binary: Boolean? = null,
)

@Serializable
data class SafetyIssue(
    val file: String,
    val kind: String,
    val detail: String,
)

@Serializable
data class SyncReq(val force: Boolean? = null)

@Serializable
data class SyncResp(
    val status: String,
    val diffStat: List<DiffFileStat>? = null,
    val safetyIssues: List<SafetyIssue>? = null,
)

@Serializable
data class UsageWindow(
    val utilization: Double,
    val resetsAt: String,
)

@Serializable
data class ExtraUsage(
    val isEnabled: Boolean,
    val monthlyLimit: Double,
    val usedCredits: Double,
    val utilization: Double,
)

@Serializable
data class UsageResp(
    val fiveHour: UsageWindow,
    val sevenDay: UsageWindow,
    val extraUsage: ExtraUsage,
)

@Serializable
data class VoiceTokenResp(
    val token: String,
    val expiresAt: String,
    val ephemeral: Boolean = false,
)

// Backend-neutral event types

@Serializable
data class EventMessage(
    val kind: EventKind,
    val ts: Long,
    val init: EventInit? = null,
    val text: EventText? = null,
    val textDelta: EventTextDelta? = null,
    val toolUse: EventToolUse? = null,
    val toolResult: EventToolResult? = null,
    val ask: EventAsk? = null,
    val usage: EventUsage? = null,
    val result: EventResult? = null,
    val system: EventSystem? = null,
    val userInput: EventUserInput? = null,
    val todo: EventTodo? = null,
)

@Serializable
data class EventInit(
    val model: String,
    val agentVersion: String,
    @SerialName("sessionID") val sessionID: String,
    val tools: List<String>,
    val cwd: String,
    val harness: String,
)

// Claude-specific event types

@Serializable
data class ClaudeEventMessage(
    val kind: ClaudeEventKind,
    val ts: Long,
    val init: ClaudeEventInit? = null,
    val text: ClaudeEventText? = null,
    val textDelta: ClaudeEventTextDelta? = null,
    val toolUse: ClaudeEventToolUse? = null,
    val toolResult: ClaudeEventToolResult? = null,
    val ask: ClaudeEventAsk? = null,
    val usage: ClaudeEventUsage? = null,
    val result: ClaudeEventResult? = null,
    val system: ClaudeEventSystem? = null,
    val userInput: ClaudeEventUserInput? = null,
    val todo: ClaudeEventTodo? = null,
)

@Serializable
data class ClaudeEventInit(
    val model: String,
    val agentVersion: String,
    @SerialName("sessionID") val sessionID: String,
    val tools: List<String>,
    val cwd: String,
)

@Serializable
data class ClaudeEventText(val text: String)

@Serializable
data class ClaudeEventTextDelta(val text: String)

@Serializable
data class ClaudeEventToolUse(
    @SerialName("toolUseID") val toolUseID: String,
    val name: String,
    val input: JsonElement,
)

@Serializable
data class ClaudeEventToolResult(
    @SerialName("toolUseID") val toolUseID: String,
    val durationMs: Long,
    val error: String? = null,
)

@Serializable
data class ClaudeAskOption(
    val label: String,
    val description: String? = null,
)

@Serializable
data class ClaudeAskQuestion(
    val question: String,
    val header: String? = null,
    val options: List<ClaudeAskOption>,
    val multiSelect: Boolean? = null,
)

@Serializable
data class ClaudeEventAsk(
    @SerialName("toolUseID") val toolUseID: String,
    val questions: List<ClaudeAskQuestion>,
)

@Serializable
data class ClaudeEventUsage(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheCreationInputTokens: Int,
    val cacheReadInputTokens: Int,
    val serviceTier: String? = null,
    val model: String,
)

@Serializable
data class ClaudeEventResult(
    val subtype: String,
    val isError: Boolean,
    val result: String,
    val diffStat: List<DiffFileStat>? = null,
    @SerialName("totalCostUSD") val totalCostUSD: Double,
    val durationMs: Long,
    @SerialName("durationAPIMs") val durationAPIMs: Long,
    val numTurns: Int,
    val usage: ClaudeEventUsage,
)

@Serializable
data class ClaudeEventSystem(val subtype: String)

@Serializable
data class ClaudeEventUserInput(val text: String)

@Serializable
data class ClaudeTodoItem(
    val content: String,
    val status: String,
    val activeForm: String? = null,
)

@Serializable
data class ClaudeEventTodo(
    @SerialName("toolUseID") val toolUseID: String,
    val todos: List<ClaudeTodoItem>,
)

@Serializable
data class EventText(val text: String)

@Serializable
data class EventTextDelta(val text: String)

@Serializable
data class EventToolUse(
    @SerialName("toolUseID") val toolUseID: String,
    val name: String,
    val input: JsonElement,
)

@Serializable
data class EventToolResult(
    @SerialName("toolUseID") val toolUseID: String,
    val durationMs: Long,
    val error: String? = null,
)

@Serializable
data class AskOption(
    val label: String,
    val description: String? = null,
)

@Serializable
data class AskQuestion(
    val question: String,
    val header: String? = null,
    val options: List<AskOption>,
    val multiSelect: Boolean? = null,
)

@Serializable
data class EventAsk(
    @SerialName("toolUseID") val toolUseID: String,
    val questions: List<AskQuestion>,
)

@Serializable
data class EventUsage(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheCreationInputTokens: Int,
    val cacheReadInputTokens: Int,
    val serviceTier: String? = null,
    val model: String,
)

@Serializable
data class EventResult(
    val subtype: String,
    val isError: Boolean,
    val result: String,
    val diffStat: List<DiffFileStat>? = null,
    @SerialName("totalCostUSD") val totalCostUSD: Double,
    val durationMs: Long,
    @SerialName("durationAPIMs") val durationAPIMs: Long,
    val numTurns: Int,
    val usage: EventUsage,
)

@Serializable
data class EventSystem(val subtype: String)

@Serializable
data class EventUserInput(val text: String)

@Serializable
data class TodoItem(
    val content: String,
    val status: String,
    val activeForm: String? = null,
)

@Serializable
data class EventTodo(
    @SerialName("toolUseID") val toolUseID: String,
    val todos: List<TodoItem>,
)

@Serializable
data class ErrorResponse(
    val error: ErrorDetails,
    val details: Map<String, JsonElement>? = null,
)

@Serializable
data class ErrorDetails(
    val code: String,
    val message: String,
)
