// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Structured API error types and constructors.
*/

/**
 * ErrorCode is a machine-readable error identifier.
 */
export type ErrorCode = string;
/**
 * Standard error codes.
 */
export const CodeBadRequest: ErrorCode = "BAD_REQUEST";
/**
 * Standard error codes.
 */
export const CodeNotFound: ErrorCode = "NOT_FOUND";
/**
 * Standard error codes.
 */
export const CodeConflict: ErrorCode = "CONFLICT";
/**
 * Standard error codes.
 */
export const CodeInternalError: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrorWithStatus is an error that carries an HTTP status code, error code,
 * and optional details map.
 */
export type ErrorWithStatus = 
    error;
/**
 * APIError is a concrete error type with status code, error code, optional
 * details, and optional wrapped error.
 */
export interface APIError {
}
/**
 * ErrorResponse is the JSON envelope for error responses.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorDetails holds the code and message within an error response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}

//////////
// source: types.go
/*
Exported request and response types for the wmao API.
*/

/**
 * RepoJSON is the JSON representation of a discovered repo.
 */
export interface RepoJSON {
  path: string;
  baseBranch: string;
}
/**
 * TaskJSON is the JSON representation sent to the frontend.
 */
export interface TaskJSON {
  id: number /* int */;
  task: string;
  repo: string;
  branch: string;
  container: string;
  state: string;
  stateUpdatedAtMs: number /* int64 */; // Unix millis UTC of last state change.
  diffStat: string;
  costUSD: number /* float64 */;
  durationMs: number /* int64 */;
  numTurns: number /* int */;
  error?: string;
  result?: string;
}
/**
 * StatusResp is a common response for mutation endpoints.
 */
export interface StatusResp {
  status: string;
}
/**
 * CreateTaskResp is the response for POST /api/v1/tasks.
 */
export interface CreateTaskResp {
  status: string;
  id: number /* int */;
}
/**
 * CreateTaskReq is the request body for POST /api/v1/tasks.
 */
export interface CreateTaskReq {
  prompt: string;
  repo: string;
}
/**
 * InputReq is the request body for POST /api/v1/tasks/{id}/input.
 */
export interface InputReq {
  prompt: string;
}
/**
 * PullResp is the response for POST /api/v1/tasks/{id}/pull.
 */
export interface PullResp {
  status: string;
  diffStat: string;
}
/**
 * EmptyReq is used for endpoints that take no request body.
 */
export interface EmptyReq {
}
