// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Structured API error types and constructors.
*/

/**
 * ErrorCode is a machine-readable error identifier.
 */
export type ErrorCode = string;
/**
 * Standard error codes.
 */
export const CodeBadRequest: ErrorCode = "BAD_REQUEST";
/**
 * Standard error codes.
 */
export const CodeNotFound: ErrorCode = "NOT_FOUND";
/**
 * Standard error codes.
 */
export const CodeConflict: ErrorCode = "CONFLICT";
/**
 * Standard error codes.
 */
export const CodeInternalError: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrorWithStatus is an error that carries an HTTP status code, error code,
 * and optional details map.
 */
export type ErrorWithStatus = 
    error;
/**
 * APIError is a concrete error type with status code, error code, optional
 * details, and optional wrapped error.
 */
export interface APIError {
}
/**
 * ErrorResponse is the JSON envelope for error responses.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorDetails holds the code and message within an error response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}

//////////
// source: events.go
/*
SSE event types sent to the frontend for task event streams.
These structs are generated into TypeScript via tygo.
*/

/**
 * EventKind identifies the type of SSE event.
 */
export type EventKind = string;
/**
 * Event kind constants.
 */
export const EventKindInit: EventKind = "init";
/**
 * Event kind constants.
 */
export const EventKindText: EventKind = "text";
/**
 * Event kind constants.
 */
export const EventKindToolUse: EventKind = "toolUse";
/**
 * Event kind constants.
 */
export const EventKindToolResult: EventKind = "toolResult";
/**
 * Event kind constants.
 */
export const EventKindAsk: EventKind = "ask";
/**
 * Event kind constants.
 */
export const EventKindUsage: EventKind = "usage";
/**
 * Event kind constants.
 */
export const EventKindResult: EventKind = "result";
/**
 * Event kind constants.
 */
export const EventKindSystem: EventKind = "system";
/**
 * Event kind constants.
 */
export const EventKindUserInput: EventKind = "userInput";
/**
 * Event kind constants.
 */
export const EventKindTodo: EventKind = "todo";
/**
 * EventMessage is a single SSE event sent to the frontend. The Kind field
 * determines which payload field is non-nil.
 */
export interface EventMessage {
  kind: EventKind;
  ts: number /* int64 */; // Unix milliseconds when the backend received this message.
  init?: EventInit; // Kind "init".
  text?: EventText; // Kind "text".
  toolUse?: EventToolUse; // Kind "toolUse".
  toolResult?: EventToolResult; // Kind "toolResult".
  ask?: EventAsk; // Kind "ask".
  usage?: EventUsage; // Kind "usage".
  result?: EventResult; // Kind "result".
  system?: EventSystem; // Kind "system".
  userInput?: EventUserInput; // Kind "userInput".
  todo?: EventTodo; // Kind "todo".
}
/**
 * EventInit is emitted once at the start of a session.
 */
export interface EventInit {
  model: string;
  agentVersion: string;
  sessionID: string;
  tools: string[];
  cwd: string;
}
/**
 * EventText is an assistant text block.
 */
export interface EventText {
  text: string;
}
/**
 * EventToolUse is emitted when the assistant invokes a tool.
 */
export interface EventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
}
/**
 * EventToolResult is emitted when a tool call completes.
 */
export interface EventToolResult {
  toolUseID: string;
  durationMs: number /* int64 */; // Server-computed; 0 if unknown.
  error?: string;
}
/**
 * AskOption is a single option in an AskUserQuestion.
 */
export interface AskOption {
  label: string;
  description?: string;
}
/**
 * AskQuestion is a single question from AskUserQuestion.
 */
export interface AskQuestion {
  question: string;
  header?: string;
  options: AskOption[];
  multiSelect?: boolean;
}
/**
 * EventAsk is emitted when the agent asks the user a question.
 */
export interface EventAsk {
  toolUseID: string;
  questions: AskQuestion[];
}
/**
 * EventUsage reports per-turn token usage.
 */
export interface EventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  serviceTier?: string;
  model: string;
}
/**
 * EventResult is emitted when the task reaches a terminal state.
 */
export interface EventResult {
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  durationMs: number /* int64 */;
  durationAPIMs: number /* int64 */;
  numTurns: number /* int */;
  usage: EventUsage;
}
/**
 * EventSystem is a generic system event (status, compact_boundary, etc.).
 */
export interface EventSystem {
  subtype: string;
}
/**
 * EventUserInput is emitted when a user sends a text message to the agent.
 */
export interface EventUserInput {
  text: string;
}
/**
 * TodoItem is a single todo entry from a TodoWrite tool call.
 */
export interface TodoItem {
  content: string;
  status: string; // "pending", "in_progress", "completed".
  activeForm?: string;
}
/**
 * EventTodo is emitted when the agent writes/updates its todo list.
 */
export interface EventTodo {
  toolUseID: string;
  todos: TodoItem[];
}

//////////
// source: types.go
/*
Exported request and response types for the caic API.
*/

/**
 * Harness identifies the coding agent harness.
 * Values must match agent.Harness constants.
 */
export type Harness = string;
/**
 * Supported agent harnesses.
 */
export const HarnessClaude: Harness = "claude";
/**
 * Supported agent harnesses.
 */
export const HarnessGemini: Harness = "gemini";
/**
 * HarnessJSON is the JSON representation of an available harness.
 */
export interface HarnessJSON {
  name: string;
}
/**
 * RepoJSON is the JSON representation of a discovered repo.
 */
export interface RepoJSON {
  path: string;
  baseBranch: string;
  repoURL?: string;
}
/**
 * TaskJSON is the JSON representation sent to the frontend.
 */
export interface TaskJSON {
  id: string;
  task: string;
  repo: string;
  repoURL?: string;
  branch: string;
  container: string;
  state: string;
  stateUpdatedAt: number /* float64 */; // Unix epoch seconds (ms precision) of last state change.
  diffStat?: DiffStat;
  costUSD: number /* float64 */;
  durationMs: number /* int64 */;
  numTurns: number /* int */;
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  error?: string;
  result?: string;
  /**
   * Per-task harness/container metadata.
   */
  harness: Harness;
  model?: string;
  agentVersion?: string;
  sessionID?: string;
  containerUptimeMs?: number /* int64 */;
  inPlanMode?: boolean;
}
/**
 * StatusResp is a common response for mutation endpoints.
 */
export interface StatusResp {
  status: string;
}
/**
 * CreateTaskResp is the response for POST /api/v1/tasks.
 */
export interface CreateTaskResp {
  status: string;
  id: string;
}
/**
 * CreateTaskReq is the request body for POST /api/v1/tasks.
 */
export interface CreateTaskReq {
  prompt: string;
  repo: string;
  model?: string;
  harness: Harness;
}
/**
 * InputReq is the request body for POST /api/v1/tasks/{id}/input.
 */
export interface InputReq {
  prompt: string;
}
/**
 * RestartReq is the request body for POST /api/v1/tasks/{id}/restart.
 */
export interface RestartReq {
  prompt: string;
}
/**
 * DiffFileStat describes changes to a single file.
 */
export interface DiffFileStat {
  path: string;
  added: number /* int */;
  deleted: number /* int */;
  binary?: boolean;
}
/**
 * DiffStat summarises the changes in a branch relative to its base.
 */
export type DiffStat = DiffFileStat[];
/**
 * SafetyIssue describes a potential problem detected before pushing to origin.
 */
export interface SafetyIssue {
  file: string;
  kind: string; // "large_binary" or "secret"
  detail: string; // Human-readable description.
}
/**
 * SyncReq is the request body for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncReq {
  force?: boolean;
}
/**
 * SyncResp is the response for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncResp {
  status: string; // "synced", "blocked", or "empty"
  diffStat?: DiffStat;
  safetyIssues?: SafetyIssue[];
}
/**
 * UsageWindow represents a single quota window (5-hour or 7-day).
 */
export interface UsageWindow {
  utilization: number /* float64 */;
  resetsAt: string;
}
/**
 * ExtraUsage represents the extra (pay-as-you-go) usage state.
 */
export interface ExtraUsage {
  isEnabled: boolean;
  monthlyLimit: number /* float64 */;
  usedCredits: number /* float64 */;
  utilization: number /* float64 */;
}
/**
 * UsageResp is the response for GET /api/v1/usage.
 */
export interface UsageResp {
  fiveHour: UsageWindow;
  sevenDay: UsageWindow;
  extraUsage: ExtraUsage;
}
/**
 * EmptyReq is used for endpoints that take no request body.
 */
export interface EmptyReq {
}
