// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go
/*
Structured API error types and constructors.
*/

/**
 * ErrorCode is a machine-readable error identifier.
 */
export type ErrorCode = string;
/**
 * Standard error codes.
 */
export const CodeBadRequest: ErrorCode = "BAD_REQUEST";
/**
 * Standard error codes.
 */
export const CodeNotFound: ErrorCode = "NOT_FOUND";
/**
 * Standard error codes.
 */
export const CodeConflict: ErrorCode = "CONFLICT";
/**
 * Standard error codes.
 */
export const CodeInternalError: ErrorCode = "INTERNAL_ERROR";
/**
 * ErrorWithStatus is an error that carries an HTTP status code, error code,
 * and optional details map.
 */
export type ErrorWithStatus = 
    error;
/**
 * APIError is a concrete error type with status code, error code, optional
 * details, and optional wrapped error.
 */
export interface APIError {
}
/**
 * ErrorResponse is the JSON envelope for error responses.
 */
export interface ErrorResponse {
  error: ErrorDetails;
  details?: { [key: string]: any};
}
/**
 * ErrorDetails holds the code and message within an error response.
 */
export interface ErrorDetails {
  code: ErrorCode;
  message: string;
}

//////////
// source: events.go
/*
SSE event types sent to the frontend for task event streams.
These structs are generated into TypeScript via tygo.

Two separate event hierarchies exist:

  - EventMessage (backend-neutral): the stable API contract consumed by the
    frontend via /api/v1/tasks/{id}/events. Every backend (Claude, Gemini,
    Codex, …) produces these events through its own converter. EventInit
    includes a Harness field so the client knows which backend produced the
    stream.

  - ClaudeEventMessage (Claude-specific): the raw stream exposed on
    /api/v1/tasks/{id}/raw_events for the Claude Code backend. When new
    backends are added, each will get its own *EventMessage type for its raw
    stream (e.g. GeminiEventMessage) while the generic EventMessage remains
    the shared frontend contract.

Each hierarchy has its own complete set of sub-event types (e.g. EventText
vs ClaudeEventText). They are structurally identical today but kept separate
so they can diverge as backends evolve independently.
*/

/**
 * EventKind identifies the type of SSE event.
 */
export type EventKind = string;
/**
 * Event kind constants.
 */
export const EventKindInit: EventKind = "init";
/**
 * Event kind constants.
 */
export const EventKindText: EventKind = "text";
/**
 * Event kind constants.
 */
export const EventKindTextDelta: EventKind = "textDelta";
/**
 * Event kind constants.
 */
export const EventKindToolUse: EventKind = "toolUse";
/**
 * Event kind constants.
 */
export const EventKindToolResult: EventKind = "toolResult";
/**
 * Event kind constants.
 */
export const EventKindAsk: EventKind = "ask";
/**
 * Event kind constants.
 */
export const EventKindUsage: EventKind = "usage";
/**
 * Event kind constants.
 */
export const EventKindResult: EventKind = "result";
/**
 * Event kind constants.
 */
export const EventKindSystem: EventKind = "system";
/**
 * Event kind constants.
 */
export const EventKindUserInput: EventKind = "userInput";
/**
 * Event kind constants.
 */
export const EventKindTodo: EventKind = "todo";
/**
 * Event kind constants.
 */
export const EventKindDiffStat: EventKind = "diffStat";
/**
 * EventMessage is a single SSE event in the backend-neutral stream
 * (/api/v1/tasks/{id}/events). All backends produce these events.
 */
export interface EventMessage {
  kind: EventKind;
  ts: number /* int64 */;
  init?: EventInit;
  text?: EventText;
  textDelta?: EventTextDelta;
  toolUse?: EventToolUse;
  toolResult?: EventToolResult;
  ask?: EventAsk;
  usage?: EventUsage;
  result?: EventResult;
  system?: EventSystem;
  userInput?: EventUserInput;
  todo?: EventTodo;
  diffStat?: EventDiffStat;
}
/**
 * EventInit is emitted once at the start of a session. It includes a Harness
 * field so the client knows which backend produced the stream.
 */
export interface EventInit {
  model: string;
  agentVersion: string;
  sessionID: string;
  tools: string[];
  cwd: string;
  harness: string;
}
/**
 * EventText is an assistant text block.
 */
export interface EventText {
  text: string;
}
/**
 * EventTextDelta is a streaming text fragment from --include-partial-messages.
 */
export interface EventTextDelta {
  text: string;
}
/**
 * EventToolUse is emitted when the assistant invokes a tool.
 */
export interface EventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
}
/**
 * EventToolResult is emitted when a tool call completes.
 */
export interface EventToolResult {
  toolUseID: string;
  durationMs: number /* int64 */; // Server-computed; 0 if unknown.
  error?: string;
}
/**
 * AskOption is a single option in an AskUserQuestion.
 */
export interface AskOption {
  label: string;
  description?: string;
}
/**
 * AskQuestion is a single question from AskUserQuestion.
 */
export interface AskQuestion {
  question: string;
  header?: string;
  options: AskOption[];
  multiSelect?: boolean;
}
/**
 * EventAsk is emitted when the agent asks the user a question.
 */
export interface EventAsk {
  toolUseID: string;
  questions: AskQuestion[];
}
/**
 * EventUsage reports per-turn token usage.
 */
export interface EventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  serviceTier?: string;
  model: string;
}
/**
 * EventResult is emitted when the task reaches a terminal state.
 */
export interface EventResult {
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  durationMs: number /* int64 */;
  durationAPIMs: number /* int64 */;
  numTurns: number /* int */;
  usage: EventUsage;
}
/**
 * EventSystem is a system event (status, compact_boundary, etc.).
 */
export interface EventSystem {
  subtype: string;
}
/**
 * EventUserInput is emitted when a user sends a text message to the agent.
 */
export interface EventUserInput {
  text: string;
}
/**
 * TodoItem is a single todo entry from a TodoWrite tool call.
 */
export interface TodoItem {
  content: string;
  status: string; // "pending", "in_progress", "completed".
  activeForm?: string;
}
/**
 * EventTodo is emitted when the agent writes/updates its todo list.
 */
export interface EventTodo {
  toolUseID: string;
  todos: TodoItem[];
}
/**
 * EventDiffStat is emitted when the relay reports updated diff statistics.
 */
export interface EventDiffStat {
  diffStat?: DiffStat;
}
/**
 * ClaudeEventKind identifies the type of SSE event in the Claude-specific raw
 * stream. Values are identical to EventKind; a separate type alias is used so
 * that future backends can diverge if needed.
 */
export type ClaudeEventKind = string;
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindInit: ClaudeEventKind = "init";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindText: ClaudeEventKind = "text";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindTextDelta: ClaudeEventKind = "textDelta";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindToolUse: ClaudeEventKind = "toolUse";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindToolResult: ClaudeEventKind = "toolResult";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindAsk: ClaudeEventKind = "ask";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindUsage: ClaudeEventKind = "usage";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindResult: ClaudeEventKind = "result";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindSystem: ClaudeEventKind = "system";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindUserInput: ClaudeEventKind = "userInput";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindTodo: ClaudeEventKind = "todo";
/**
 * Claude-specific event kind constants.
 */
export const ClaudeEventKindDiffStat: ClaudeEventKind = "diffStat";
/**
 * ClaudeEventMessage is a single SSE event in the Claude Code raw stream
 * (/api/v1/tasks/{id}/raw_events). When additional backends are added, each
 * will define its own *EventMessage (e.g. GeminiEventMessage) for its raw
 * stream. The Kind field determines which payload field is non-nil.
 * All sub-event types are Claude-specific duplicates of the generic types.
 * They are structurally identical today but will diverge as backends evolve.
 */
export interface ClaudeEventMessage {
  kind: ClaudeEventKind;
  ts: number /* int64 */; // Unix milliseconds when the backend received this message.
  init?: ClaudeEventInit; // Kind "init".
  text?: ClaudeEventText; // Kind "text".
  textDelta?: ClaudeEventTextDelta; // Kind "textDelta".
  toolUse?: ClaudeEventToolUse; // Kind "toolUse".
  toolResult?: ClaudeEventToolResult; // Kind "toolResult".
  ask?: ClaudeEventAsk; // Kind "ask".
  usage?: ClaudeEventUsage; // Kind "usage".
  result?: ClaudeEventResult; // Kind "result".
  system?: ClaudeEventSystem; // Kind "system".
  userInput?: ClaudeEventUserInput; // Kind "userInput".
  todo?: ClaudeEventTodo; // Kind "todo".
  diffStat?: ClaudeEventDiffStat; // Kind "diffStat".
}
/**
 * ClaudeEventInit is emitted once at the start of a Claude session. Unlike the
 * generic EventInit it omits the Harness field (always "claude" for this stream).
 */
export interface ClaudeEventInit {
  model: string;
  agentVersion: string;
  sessionID: string;
  tools: string[];
  cwd: string;
}
/**
 * ClaudeEventText is an assistant text block in the Claude raw stream.
 */
export interface ClaudeEventText {
  text: string;
}
/**
 * ClaudeEventTextDelta is a streaming text fragment in the Claude raw stream.
 */
export interface ClaudeEventTextDelta {
  text: string;
}
/**
 * ClaudeEventToolUse is emitted when Claude invokes a tool.
 */
export interface ClaudeEventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
}
/**
 * ClaudeEventToolResult is emitted when a Claude tool call completes.
 */
export interface ClaudeEventToolResult {
  toolUseID: string;
  durationMs: number /* int64 */;
  error?: string;
}
/**
 * ClaudeAskOption is a single option in a Claude AskUserQuestion.
 */
export interface ClaudeAskOption {
  label: string;
  description?: string;
}
/**
 * ClaudeAskQuestion is a single question from Claude's AskUserQuestion.
 */
export interface ClaudeAskQuestion {
  question: string;
  header?: string;
  options: ClaudeAskOption[];
  multiSelect?: boolean;
}
/**
 * ClaudeEventAsk is emitted when Claude asks the user a question.
 */
export interface ClaudeEventAsk {
  toolUseID: string;
  questions: ClaudeAskQuestion[];
}
/**
 * ClaudeEventUsage reports per-turn token usage in the Claude raw stream.
 */
export interface ClaudeEventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  serviceTier?: string;
  model: string;
}
/**
 * ClaudeEventResult is emitted when a Claude task reaches a terminal state.
 */
export interface ClaudeEventResult {
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  durationMs: number /* int64 */;
  durationAPIMs: number /* int64 */;
  numTurns: number /* int */;
  usage: ClaudeEventUsage;
}
/**
 * ClaudeEventSystem is a system event in the Claude raw stream.
 */
export interface ClaudeEventSystem {
  subtype: string;
}
/**
 * ClaudeEventUserInput is emitted when a user sends a text message to Claude.
 */
export interface ClaudeEventUserInput {
  text: string;
}
/**
 * ClaudeTodoItem is a single todo entry from a Claude TodoWrite tool call.
 */
export interface ClaudeTodoItem {
  content: string;
  status: string;
  activeForm?: string;
}
/**
 * ClaudeEventTodo is emitted when Claude writes/updates its todo list.
 */
export interface ClaudeEventTodo {
  toolUseID: string;
  todos: ClaudeTodoItem[];
}
/**
 * ClaudeEventDiffStat is emitted when the relay reports updated diff statistics.
 */
export interface ClaudeEventDiffStat {
  diffStat?: DiffStat;
}

//////////
// source: types.go
/*
Exported request and response types for the caic API.
*/

/**
 * Harness identifies the coding agent harness.
 * Values must match agent.Harness constants.
 */
export type Harness = string;
/**
 * Supported agent harnesses.
 */
export const HarnessClaude: Harness = "claude";
/**
 * Supported agent harnesses.
 */
export const HarnessGemini: Harness = "gemini";
/**
 * HarnessJSON is the JSON representation of an available harness.
 */
export interface HarnessJSON {
  name: string;
  models: string[];
}
/**
 * ConfigJSON reports server capabilities to the frontend.
 */
export interface ConfigJSON {
  tailscaleAvailable: boolean;
  usbAvailable: boolean;
  displayAvailable: boolean;
}
/**
 * RepoJSON is the JSON representation of a discovered repo.
 */
export interface RepoJSON {
  path: string;
  baseBranch: string;
  repoURL?: string;
}
/**
 * TaskJSON is the JSON representation sent to the frontend.
 */
export interface TaskJSON {
  id: string;
  task: string;
  repo: string;
  repoURL?: string;
  branch: string;
  container: string;
  state: string;
  stateUpdatedAt: number /* float64 */; // Unix epoch seconds (ms precision) of last state change.
  diffStat?: DiffStat;
  costUSD: number /* float64 */;
  durationMs: number /* int64 */;
  numTurns: number /* int */;
  cumulativeInputTokens: number /* int */;
  cumulativeOutputTokens: number /* int */;
  cumulativeCacheCreationInputTokens: number /* int */;
  cumulativeCacheReadInputTokens: number /* int */;
  activeInputTokens: number /* int */; // Last turn's non-cached input tokens (including cache creation).
  activeCacheReadTokens: number /* int */; // Last turn's cache-read input tokens.
  error?: string;
  result?: string;
  /**
   * Per-task harness/container metadata.
   */
  harness: Harness;
  model?: string;
  agentVersion?: string;
  sessionID?: string;
  containerUptimeMs?: number /* int64 */;
  inPlanMode?: boolean;
  tailscale?: string; // Tailscale URL (https://fqdn) or "true" if enabled but FQDN unknown.
  usb?: boolean;
  display?: boolean;
}
/**
 * StatusResp is a common response for mutation endpoints.
 */
export interface StatusResp {
  status: string;
}
/**
 * CreateTaskResp is the response for POST /api/v1/tasks.
 */
export interface CreateTaskResp {
  status: string;
  id: string;
}
/**
 * CreateTaskReq is the request body for POST /api/v1/tasks.
 */
export interface CreateTaskReq {
  prompt: string;
  repo: string;
  model?: string;
  harness: Harness;
  image?: string;
  tailscale?: boolean;
  usb?: boolean;
  display?: boolean;
}
/**
 * InputReq is the request body for POST /api/v1/tasks/{id}/input.
 */
export interface InputReq {
  prompt: string;
}
/**
 * RestartReq is the request body for POST /api/v1/tasks/{id}/restart.
 */
export interface RestartReq {
  prompt: string;
}
/**
 * DiffFileStat describes changes to a single file.
 */
export interface DiffFileStat {
  path: string;
  added: number /* int */;
  deleted: number /* int */;
  binary?: boolean;
}
/**
 * DiffStat summarises the changes in a branch relative to its base.
 */
export type DiffStat = DiffFileStat[];
/**
 * SafetyIssue describes a potential problem detected before pushing to origin.
 */
export interface SafetyIssue {
  file: string;
  kind: string; // "large_binary" or "secret"
  detail: string; // Human-readable description.
}
/**
 * SyncReq is the request body for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncReq {
  force?: boolean;
}
/**
 * SyncResp is the response for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncResp {
  status: string; // "synced", "blocked", or "empty"
  diffStat?: DiffStat;
  safetyIssues?: SafetyIssue[];
}
/**
 * UsageWindow represents a single quota window (5-hour or 7-day).
 */
export interface UsageWindow {
  utilization: number /* float64 */;
  resetsAt: string;
}
/**
 * ExtraUsage represents the extra (pay-as-you-go) usage state.
 */
export interface ExtraUsage {
  isEnabled: boolean;
  monthlyLimit: number /* float64 */;
  usedCredits: number /* float64 */;
  utilization: number /* float64 */;
}
/**
 * UsageResp is the response for GET /api/v1/usage.
 */
export interface UsageResp {
  fiveHour: UsageWindow;
  sevenDay: UsageWindow;
  extraUsage: ExtraUsage;
}
/**
 * VoiceTokenResp is the response for GET /api/v1/voice/token.
 */
export interface VoiceTokenResp {
  token: string;
  expiresAt: string;
  ephemeral: boolean;
}
/**
 * EmptyReq is used for endpoints that take no request body.
 */
export interface EmptyReq {
}
